error: 'HTTPSConnectionPool(host=''cve.circl.lu'', port=443): Max retries exceeded
  with url: /api/last (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
  object at 0xXXXX>: Failed to establish a new connection: [Errno 101] Network is
  unreachable''))'
generated_at: '2025-10-16T22:09:42Z'
items: []
