error: 'HTTPSConnectionPool(host=''cve.circl.lu'', port=443): Max retries exceeded
  with url: /api/last (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection
  object at 0xXXXX>: Failed to establish a new connection: [Errno 101] Network is
  unreachable''))'
fetched_at: '2025-10-16T23:53:44Z'
generated_at: '2025-10-16T23:53:44Z'
hash: f3f8475cf7c5bb94a2cc14051e976c934436e6eb748d1ac57a60001d5aec5701
items: []
source_url: https://cve.circl.lu/api/last
